<?php

declare(strict_types=1);

namespace Sift\Tools\Behat;

use JsonException;
use Sift\Core\ErrorCode;
use Sift\Core\ItemType;
use Sift\Exceptions\UserFacingException;
use Sift\Tools\Testing\ReportPathNormalizer;

final readonly class BehatParser
{
    public function __construct(
        private ReportPathNormalizer $pathNormalizer = new ReportPathNormalizer(),
        private int $maxBytes = 5_242_880,
    ) {}

    /**
     * @param list<string> $generatedFiles
     */
    public function parse(string $path, string $cwd, array $generatedFiles): BehatReport
    {
        $document = $this->read($path, $generatedFiles);
        $tests = $this->optionalInt($document, 'tests');
        $failed = $this->optionalInt($document, 'failed');
        $pending = $this->optionalInt($document, 'pending');
        $undefined = $this->optionalInt($document, 'undefined');
        $skipped = $this->optionalInt($document, 'skipped');
        $items = $this->items($document, $cwd);
        $errors = $pending + $undefined;
        $summary = [
            'tests' => $tests,
            'passed' => max(0, $tests - $failed - $errors - $skipped),
            'failures' => $failed,
            'errors' => $errors,
            'skipped' => $skipped,
            'pending' => $pending,
            'undefined' => $undefined,
        ];
        $duration = $document['time'] ?? null;

        if (is_int($duration) || is_float($duration)) {
            $summary['duration_seconds'] = (float) $duration;
        }

        return new BehatReport(
            summary: $summary,
            items: $items,
            findings: max($failed + $errors, count($items)),
        );
    }

    /**
     * @param list<string> $generatedFiles
     *
     * @return array<string, mixed>
     */
    private function read(string $path, array $generatedFiles): array
    {
        $realPath = realpath($path);

        if (! is_string($realPath) || ! is_file($realPath)) {
            throw $this->parseFailure('Missing or invalid Behat JSON file.');
        }

        $realGenerated = [];

        foreach ($generatedFiles as $generatedFile) {
            $generatedPath = realpath($generatedFile);

            if (is_string($generatedPath) && is_file($generatedPath)) {
                $realGenerated[] = $generatedPath;
            }
        }

        if (! in_array($realPath, $realGenerated, true)) {
            throw $this->parseFailure('Behat JSON file was not generated by this execution.');
        }

        $size = filesize($realPath);

        if (! is_int($size) || $size > $this->maxBytes) {
            throw $this->parseFailure('Behat JSON file is too large.');
        }

        $contents = file_get_contents($realPath);

        if (! is_string($contents) || trim($contents) === '') {
            throw $this->parseFailure('Behat JSON file is empty.');
        }

        try {
            return $this->object(json_decode($contents, true, 512, JSON_THROW_ON_ERROR), 'root');
        } catch (JsonException $jsonException) {
            throw $this->parseFailure($jsonException->getMessage());
        }
    }

    /**
     * @param array<string, mixed> $document
     *
     * @return list<array<string, mixed>>
     */
    private function items(array $document, string $cwd): array
    {
        $items = [];

        foreach ($this->list($document['suites'] ?? [], 'suites') as $suiteValue) {
            $suite = $this->object($suiteValue, 'suites[]');
            $suiteName = $this->string($suite, 'name');

            foreach ($this->list($suite['features'] ?? [], 'features') as $featureValue) {
                $feature = $this->object($featureValue, 'features[]');
                $featureName = $this->string($feature, 'name');

                foreach ($this->list($feature['scenarios'] ?? [], 'scenarios') as $scenarioValue) {
                    $scenario = $this->object($scenarioValue, 'scenarios[]');
                    $scenarioName = $this->string($scenario, 'name');
                    $status = $this->string($scenario, 'status');
                    $file = $this->string($scenario, 'file');
                    $line = $scenario['line'] ?? null;

                    if ($line !== null && ! is_int($line)) {
                        throw $this->parseFailure('Behat scenario "line" must be an integer.');
                    }

                    foreach ($this->list($scenario['failures'] ?? [], 'failures') as $failureValue) {
                        $failure = $this->object($failureValue, 'failures[]');
                        $failureType = $this->string($failure, 'type');
                        $item = [
                            'type' => $failureType === 'failed' ? ItemType::TestFailure->value : ItemType::TestError->value,
                            'test' => $scenarioName,
                            'suite' => $suiteName,
                            'feature' => $featureName,
                            'file' => $this->pathNormalizer->normalize($file, $cwd),
                        ];

                        if ($line !== null) {
                            $item['line'] = $line;
                        }

                        $item['message'] = $this->string($failure, 'message');
                        $item['failure_type'] = $failureType;
                        $items[] = $item;
                    }

                    if ($status !== 'passed' && $status !== 'skipped' && ! isset($scenario['failures'])) {
                        $items[] = [
                            'type' => ItemType::TestError->value,
                            'test' => $scenarioName,
                            'suite' => $suiteName,
                            'feature' => $featureName,
                            'file' => $this->pathNormalizer->normalize($file, $cwd),
                            ...($line === null ? [] : ['line' => $line]),
                            'message' => sprintf('Behat scenario finished with status "%s".', $status),
                            'failure_type' => $status,
                        ];
                    }
                }
            }
        }

        return $items;
    }

    /**
     * @return array<string, mixed>
     */
    private function object(mixed $value, string $field): array
    {
        if (! is_array($value) || array_is_list($value)) {
            throw $this->parseFailure(sprintf('Behat "%s" must be an object.', $field));
        }

        $object = [];

        foreach ($value as $key => $item) {
            if (! is_string($key)) {
                throw $this->parseFailure(sprintf('Behat "%s" must use string keys.', $field));
            }

            $object[$key] = $item;
        }

        return $object;
    }

    /**
     * @return list<mixed>
     */
    private function list(mixed $value, string $field): array
    {
        if (! is_array($value) || ! array_is_list($value)) {
            throw $this->parseFailure(sprintf('Behat "%s" must be a list.', $field));
        }

        return $value;
    }

    /**
     * @param array<string, mixed> $values
     */
    private function optionalInt(array $values, string $key): int
    {
        $value = $values[$key] ?? 0;

        if (! is_int($value)) {
            throw $this->parseFailure(sprintf('Behat "%s" must be an integer.', $key));
        }

        return $value;
    }

    /**
     * @param array<string, mixed> $values
     */
    private function string(array $values, string $key): string
    {
        $value = $values[$key] ?? null;

        if (! is_string($value) || $value === '') {
            throw $this->parseFailure(sprintf('Behat "%s" must be a non-empty string.', $key));
        }

        return $value;
    }

    private function parseFailure(string $reason): UserFacingException
    {
        return UserFacingException::withContext(
            errorCode: ErrorCode::ParseFailure,
            message: 'Unable to parse Behat JSON output.',
            hint: 'Use --debug to inspect limited raw output snippets.',
            context: ['reason' => $reason],
        );
    }
}
