<?php

declare(strict_types=1);

namespace Sift\Tools\Testing;

use Sift\Core\ErrorCode;
use Sift\Exceptions\UserFacingException;
use SimpleXMLElement;

final readonly class CloverCoverageParser
{
    private GeneratedXmlReader $xmlReader;

    public function __construct(
        int $maxBytes = 5_242_880,
        ?GeneratedXmlReader $xmlReader = null,
        private ReportPathNormalizer $pathNormalizer = new ReportPathNormalizer(),
    ) {
        $this->xmlReader = $xmlReader ?? new GeneratedXmlReader(
            label: 'Clover coverage XML',
            maxBytes: $maxBytes,
            hint: 'Use the Clover file generated by the current tool run.',
        );
    }

    /**
     * @param list<string> $generatedFiles
     */
    public function parse(string $path, string $cwd, array $generatedFiles, ?float $minimum): CloverCoverageReport
    {
        $xml = $this->xmlReader->read($path, $generatedFiles);
        $coveragePercent = $this->projectCoveragePercent($xml);

        if ($coveragePercent === null) {
            throw $this->parseFailure('Unable to find Clover project metrics.', ['path' => $path]);
        }

        $minimum = $minimum === null ? null : round($minimum, 2);
        $filesBelowMinimum = $minimum === null ? [] : $this->filesBelowMinimum($xml, $cwd, $minimum);

        return new CloverCoverageReport(
            coveragePercent: $coveragePercent,
            minimum: $minimum,
            thresholdFailed: $minimum !== null && $coveragePercent + 0.00001 < $minimum,
            filesBelowMinimum: $filesBelowMinimum,
        );
    }

    private function projectCoveragePercent(SimpleXMLElement $xml): ?float
    {
        $metrics = $xml->xpath('/coverage/project/metrics') ?: $xml->xpath('//project/metrics');

        if (! is_array($metrics) || ! ($metrics[0] ?? null) instanceof SimpleXMLElement) {
            return null;
        }

        return $this->coveragePercentFromMetrics($metrics[0]);
    }

    /**
     * @return list<array{file: string, percent: float}>
     */
    private function filesBelowMinimum(SimpleXMLElement $xml, string $cwd, float $minimum): array
    {
        $files = $xml->xpath('//file');

        if (! is_array($files)) {
            return [];
        }

        $belowMinimum = [];

        foreach ($files as $fileNode) {
            $entry = $this->fileCoverage($fileNode, $cwd);
            if ($entry === null) {
                continue;
            }

            if ($entry['percent'] + 0.00001 >= $minimum) {
                continue;
            }

            $belowMinimum[] = $entry;
        }

        usort(
            $belowMinimum,
            static fn(array $left, array $right): int => ($left['percent'] <=> $right['percent'])
                ?: strcmp($left['file'], $right['file']),
        );

        return $belowMinimum;
    }

    /**
     * @return array{file: string, percent: float}|null
     */
    private function fileCoverage(SimpleXMLElement $fileNode, string $cwd): ?array
    {
        $file = trim((string) $fileNode['name']);

        if ($file === '') {
            return null;
        }

        $percent = $this->coveragePercentFromMetrics($fileNode->metrics[0] ?? null);

        if ($percent === null) {
            return null;
        }

        return [
            'file' => $this->pathNormalizer->normalize($file, $cwd),
            'percent' => $percent,
        ];
    }

    private function coveragePercentFromMetrics(mixed $metrics): ?float
    {
        if (! $metrics instanceof SimpleXMLElement) {
            return null;
        }

        foreach ([
            ['coveredstatements', 'statements'],
            ['coveredelements', 'elements'],
            ['coveredmethods', 'methods'],
        ] as [$coveredKey, $totalKey]) {
            $covered = $this->intAttribute($metrics, $coveredKey);
            $total = $this->intAttribute($metrics, $totalKey);

            if ($total <= 0) {
                continue;
            }

            return round(($covered / $total) * 100, 2);
        }

        return null;
    }

    private function intAttribute(SimpleXMLElement $node, string $name): int
    {
        $value = trim((string) $node[$name]);

        return ctype_digit($value) ? (int) $value : 0;
    }

    /**
     * @param array<string, mixed> $context
     */
    private function parseFailure(string $message, array $context = []): UserFacingException
    {
        return UserFacingException::withContext(
            errorCode: ErrorCode::ParseFailure,
            message: $message,
            hint: 'Use the Clover file generated by the current tool run.',
            context: $context,
        );
    }
}
