<?php

declare(strict_types=1);

namespace Sift\Tools\Testing;

use InvalidArgumentException;
use Sift\Core\ErrorCode;
use Sift\Exceptions\UserFacingException;
use SimpleXMLElement;

final readonly class GeneratedXmlReader
{
    public function __construct(
        private string $label,
        private int $maxBytes,
        private string $hint,
    ) {
        if (trim($label) === '') {
            throw new InvalidArgumentException('XML reader label cannot be empty.');
        }

        if ($maxBytes <= 0) {
            throw new InvalidArgumentException('XML reader max bytes must be greater than zero.');
        }
    }

    /**
     * @param list<string> $generatedFiles
     */
    public function read(string $path, array $generatedFiles): SimpleXMLElement
    {
        $realPath = $this->realFile($path);

        if (! in_array($realPath, $this->realGeneratedFiles($generatedFiles), true)) {
            throw $this->parseFailure(sprintf('%s file was not generated by this execution.', $this->label), ['path' => $path]);
        }

        $size = filesize($realPath);

        if (! is_int($size) || $size > $this->maxBytes) {
            throw $this->parseFailure(sprintf('%s file is too large.', $this->label), [
                'path' => $path,
                'max_bytes' => $this->maxBytes,
            ]);
        }

        $contents = file_get_contents($realPath);

        if (! is_string($contents)) {
            throw $this->parseFailure(sprintf('Could not read %s file.', $this->label), ['path' => $path]);
        }

        if (preg_match('/<!DOCTYPE\b/i', $contents) === 1) {
            throw $this->parseFailure(sprintf('%s doctype is not allowed.', $this->label), ['path' => $path]);
        }

        return $this->loadXml($contents, $path);
    }

    private function realFile(string $path): string
    {
        $realPath = realpath($path);

        if (! is_string($realPath) || ! is_file($realPath)) {
            throw $this->parseFailure(sprintf('Missing or invalid %s file.', $this->label), ['path' => $path]);
        }

        return $realPath;
    }

    /**
     * @param list<string> $paths
     *
     * @return list<string>
     */
    private function realGeneratedFiles(array $paths): array
    {
        $realPaths = [];

        foreach ($paths as $path) {
            $realPath = realpath($path);

            if (is_string($realPath) && is_file($realPath)) {
                $realPaths[] = $realPath;
            }
        }

        return array_values(array_unique($realPaths));
    }

    private function loadXml(string $contents, string $path): SimpleXMLElement
    {
        $previous = libxml_use_internal_errors(true);
        libxml_clear_errors();

        $xml = simplexml_load_string(
            $contents,
            SimpleXMLElement::class,
            LIBXML_NONET | LIBXML_NOERROR | LIBXML_NOWARNING | LIBXML_COMPACT,
        );

        $errors = libxml_get_errors();
        libxml_clear_errors();
        libxml_use_internal_errors($previous);

        if (! $xml instanceof SimpleXMLElement) {
            throw $this->parseFailure(sprintf('Unable to parse %s output.', $this->label), [
                'path' => $path,
                'errors' => array_map(
                    static fn(\LibXMLError $error): string => trim($error->message),
                    $errors,
                ),
            ]);
        }

        return $xml;
    }

    /**
     * @param array<string, mixed> $context
     */
    private function parseFailure(string $message, array $context = []): UserFacingException
    {
        return UserFacingException::withContext(
            errorCode: ErrorCode::ParseFailure,
            message: $message,
            hint: $this->hint,
            context: $context,
        );
    }
}
