<?php

declare(strict_types=1);

namespace Sift\Tools\Testing;

use Sift\Core\ItemType;
use SimpleXMLElement;

final readonly class JunitParser
{
    private GeneratedXmlReader $xmlReader;

    public function __construct(
        int $maxBytes = 5_242_880,
        ?GeneratedXmlReader $xmlReader = null,
        private ReportPathNormalizer $pathNormalizer = new ReportPathNormalizer(),
    ) {
        $this->xmlReader = $xmlReader ?? new GeneratedXmlReader(
            label: 'JUnit XML',
            maxBytes: $maxBytes,
            hint: 'Use the JUnit file generated by the current tool run.',
        );
    }

    /**
     * @param list<string> $generatedFiles
     */
    public function parse(string $path, string $cwd, array $generatedFiles): JunitReport
    {
        return $this->parseXml($this->xmlReader->read($path, $generatedFiles), $cwd);
    }

    private function parseXml(SimpleXMLElement $xml, string $cwd): JunitReport
    {
        $tests = 0;
        $failures = 0;
        $errors = 0;
        $skipped = 0;
        $items = [];

        foreach ($this->testCases($xml) as $testCase) {
            ++$tests;
            $test = $this->attribute($testCase, 'name') ?: 'unknown';
            $file = $this->fileFromTestCase($testCase, $cwd);
            $line = $this->intAttribute($testCase, 'line');

            foreach ($testCase->failure as $failure) {
                ++$failures;
                $items[] = $this->issueItem(ItemType::TestFailure, $test, $file, $line, $failure, $cwd);
            }

            foreach ($testCase->error as $error) {
                ++$errors;
                $items[] = $this->issueItem(ItemType::TestError, $test, $file, $line, $error, $cwd);
            }

            foreach ($testCase->skipped as $skip) {
                ++$skipped;
            }
        }

        return new JunitReport($tests, $failures, $errors, $skipped, $items);
    }

    /**
     * @return list<SimpleXMLElement>
     */
    private function testCases(SimpleXMLElement $xml): array
    {
        $nodes = $xml->xpath('//testcase');

        if (! is_array($nodes)) {
            return [];
        }

        return array_values($nodes);
    }

    private function fileFromTestCase(SimpleXMLElement $testCase, string $cwd): ?string
    {
        $file = $this->attribute($testCase, 'file');

        if ($file !== '') {
            return $this->pathNormalizer->normalize($file, $cwd);
        }

        $class = $this->attribute($testCase, 'classname') ?: $this->attribute($testCase, 'class');

        return $class === '' ? null : str_replace('\\', '/', $class);
    }

    /**
     * @return array<string, mixed>
     */
    private function issueItem(
        ItemType $type,
        string $test,
        ?string $file,
        ?int $line,
        SimpleXMLElement $node,
        string $cwd,
    ): array {
        $message = $this->message($node);
        $location = $this->locationFromMessage($message, $cwd);

        if ($location !== null) {
            $file = $location['file'];
            $line = $location['line'];
            $message = str_replace($location['raw_file'], $location['file'], $message);
        }

        $item = [
            'type' => $type->value,
            'test' => $test,
        ];

        if ($file !== null && $file !== '') {
            $item['file'] = $file;
        }

        $message = trim($message);

        if ($message !== '') {
            $item['message'] = $message;
        }

        if ($line !== null) {
            $item['line'] = $line;
        }

        return $item;
    }

    private function message(SimpleXMLElement $node): string
    {
        $attribute = $this->attribute($node, 'message');
        $details = trim((string) $node);

        if ($attribute === '') {
            return $details;
        }

        if ($details === '' || $details === $attribute) {
            return $attribute;
        }

        if (str_contains($details, $attribute)) {
            return $details;
        }

        return $attribute . "\n" . $details;
    }

    /**
     * @return array{raw_file: string, file: string, line: int}|null
     */
    private function locationFromMessage(string $message, string $cwd): ?array
    {
        if (preg_match('~\b(?:at|in|Thrown at)\s+(.+?\.php):(\d+)\b~i', $message, $matches) !== 1) {
            return null;
        }

        return [
            'raw_file' => $matches[1],
            'file' => $this->pathNormalizer->normalize($matches[1], $cwd),
            'line' => (int) $matches[2],
        ];
    }

    private function attribute(SimpleXMLElement $node, string $name): string
    {
        return trim((string) $node[$name]);
    }

    private function intAttribute(SimpleXMLElement $node, string $name): ?int
    {
        $value = $this->attribute($node, $name);

        return ctype_digit($value) ? (int) $value : null;
    }
}
