<?php

declare(strict_types=1);

namespace Sift\Tools\Testing;

use InvalidArgumentException;
use Sift\Core\ErrorCode;
use Sift\Core\ItemType;
use Sift\Exceptions\UserFacingException;
use SimpleXMLElement;

final readonly class JunitParser
{
    public function __construct(
        private int $maxBytes = 5_242_880,
    ) {
        if ($maxBytes <= 0) {
            throw new InvalidArgumentException('JUnit parser max bytes must be greater than zero.');
        }
    }

    /**
     * @param list<string> $generatedFiles
     */
    public function parse(string $path, string $cwd, array $generatedFiles): JunitReport
    {
        $realPath = $this->realFile($path);

        if (! in_array($realPath, $this->realGeneratedFiles($generatedFiles), true)) {
            throw $this->parseFailure('JUnit XML file was not generated by this execution.', ['path' => $path]);
        }

        $size = filesize($realPath);

        if (! is_int($size) || $size > $this->maxBytes) {
            throw $this->parseFailure('JUnit XML file is too large.', [
                'path' => $path,
                'max_bytes' => $this->maxBytes,
            ]);
        }

        $contents = file_get_contents($realPath);

        if (! is_string($contents)) {
            throw $this->parseFailure('Could not read JUnit XML file.', ['path' => $path]);
        }

        if (preg_match('/<!DOCTYPE\b/i', $contents) === 1) {
            throw $this->parseFailure('JUnit XML doctype is not allowed.', ['path' => $path]);
        }

        $xml = $this->loadXml($contents, $path);

        return $this->parseXml($xml, $cwd);
    }

    private function realFile(string $path): string
    {
        $realPath = realpath($path);

        if (! is_string($realPath) || ! is_file($realPath)) {
            throw $this->parseFailure('Missing or invalid JUnit XML file.', ['path' => $path]);
        }

        return $realPath;
    }

    /**
     * @param list<string> $paths
     *
     * @return list<string>
     */
    private function realGeneratedFiles(array $paths): array
    {
        $realPaths = [];

        foreach ($paths as $path) {
            $realPath = realpath($path);

            if (is_string($realPath) && is_file($realPath)) {
                $realPaths[] = $realPath;
            }
        }

        return array_values(array_unique($realPaths));
    }

    private function loadXml(string $contents, string $path): SimpleXMLElement
    {
        $previous = libxml_use_internal_errors(true);
        libxml_clear_errors();

        $xml = simplexml_load_string(
            $contents,
            SimpleXMLElement::class,
            LIBXML_NONET | LIBXML_NOERROR | LIBXML_NOWARNING | LIBXML_COMPACT,
        );

        $errors = libxml_get_errors();
        libxml_clear_errors();
        libxml_use_internal_errors($previous);

        if (! $xml instanceof SimpleXMLElement) {
            throw $this->parseFailure('Unable to parse JUnit XML output.', [
                'path' => $path,
                'errors' => array_map(
                    static fn(\LibXMLError $error): string => trim($error->message),
                    $errors,
                ),
            ]);
        }

        return $xml;
    }

    private function parseXml(SimpleXMLElement $xml, string $cwd): JunitReport
    {
        $tests = 0;
        $failures = 0;
        $errors = 0;
        $skipped = 0;
        $items = [];

        foreach ($this->testCases($xml) as $testCase) {
            ++$tests;
            $test = $this->attribute($testCase, 'name') ?: 'unknown';
            $file = $this->fileFromTestCase($testCase, $cwd);
            $line = $this->intAttribute($testCase, 'line');

            foreach ($testCase->failure as $failure) {
                ++$failures;
                $items[] = $this->issueItem(ItemType::TestFailure, $test, $file, $line, $failure, $cwd);
            }

            foreach ($testCase->error as $error) {
                ++$errors;
                $items[] = $this->issueItem(ItemType::TestError, $test, $file, $line, $error, $cwd);
            }

            foreach ($testCase->skipped as $skip) {
                ++$skipped;
            }
        }

        return new JunitReport($tests, $failures, $errors, $skipped, $items);
    }

    /**
     * @return list<SimpleXMLElement>
     */
    private function testCases(SimpleXMLElement $xml): array
    {
        $nodes = $xml->xpath('//testcase');

        if (! is_array($nodes)) {
            return [];
        }

        return array_values($nodes);
    }

    private function fileFromTestCase(SimpleXMLElement $testCase, string $cwd): ?string
    {
        $file = $this->attribute($testCase, 'file');

        if ($file !== '') {
            return $this->normalizePath($file, $cwd);
        }

        $class = $this->attribute($testCase, 'classname') ?: $this->attribute($testCase, 'class');

        return $class === '' ? null : str_replace('\\', '/', $class);
    }

    /**
     * @return array<string, mixed>
     */
    private function issueItem(
        ItemType $type,
        string $test,
        ?string $file,
        ?int $line,
        SimpleXMLElement $node,
        string $cwd,
    ): array {
        $message = $this->message($node);
        $location = $this->locationFromMessage($message, $cwd);

        if ($location !== null) {
            $file = $location['file'];
            $line = $location['line'];
            $message = str_replace($location['raw_file'], $location['file'], $message);
        }

        $item = [
            'type' => $type->value,
            'test' => $test,
        ];

        if ($file !== null && $file !== '') {
            $item['file'] = $file;
        }

        $message = trim($message);

        if ($message !== '') {
            $item['message'] = $message;
        }

        if ($line !== null) {
            $item['line'] = $line;
        }

        return $item;
    }

    private function message(SimpleXMLElement $node): string
    {
        $attribute = $this->attribute($node, 'message');
        $details = trim((string) $node);

        if ($attribute === '') {
            return $details;
        }

        if ($details === '' || $details === $attribute) {
            return $attribute;
        }

        if (str_contains($details, $attribute)) {
            return $details;
        }

        return $attribute . "\n" . $details;
    }

    /**
     * @return array{raw_file: string, file: string, line: int}|null
     */
    private function locationFromMessage(string $message, string $cwd): ?array
    {
        if (preg_match('~\b(?:at|in|Thrown at)\s+(.+?\.php):(\d+)\b~i', $message, $matches) !== 1) {
            return null;
        }

        return [
            'raw_file' => $matches[1],
            'file' => $this->normalizePath($matches[1], $cwd),
            'line' => (int) $matches[2],
        ];
    }

    private function normalizePath(string $path, string $cwd): string
    {
        $normalized = str_replace('\\', '/', trim($path));
        $separator = strpos($normalized, '::');

        if ($separator !== false) {
            $normalized = substr($normalized, 0, $separator);
        }

        $cwd = rtrim(str_replace('\\', '/', $cwd), '/');
        $lowerPath = strtolower($normalized);
        $lowerCwd = strtolower($cwd);

        if ($cwd !== '' && $lowerPath === $lowerCwd) {
            return '';
        }

        if ($cwd !== '' && str_starts_with($lowerPath, $lowerCwd . '/')) {
            return ltrim(substr($normalized, strlen($cwd)), '/');
        }

        return $normalized;
    }

    private function attribute(SimpleXMLElement $node, string $name): string
    {
        return trim((string) $node[$name]);
    }

    private function intAttribute(SimpleXMLElement $node, string $name): ?int
    {
        $value = $this->attribute($node, $name);

        return ctype_digit($value) ? (int) $value : null;
    }

    /**
     * @param array<string, mixed> $context
     */
    private function parseFailure(string $message, array $context = []): UserFacingException
    {
        return UserFacingException::withContext(
            errorCode: ErrorCode::ParseFailure,
            message: $message,
            hint: 'Use the JUnit file generated by the current tool run.',
            context: $context,
        );
    }
}
