<?php

declare(strict_types=1);

namespace Sift\Tools\Infection;

use Sift\Core\ErrorCode;
use Sift\Core\ItemType;
use Sift\Exceptions\UserFacingException;
use Sift\Tools\Testing\ReportPathNormalizer;
use Throwable;

final readonly class InfectionParser
{
    public function __construct(
        private ReportPathNormalizer $pathNormalizer = new ReportPathNormalizer(),
        private int $maxBytes = 5242880,
    ) {}

    /**
     * @param list<string> $generatedFiles
     */
    public function parse(string $path, string $cwd, array $generatedFiles): InfectionReport
    {
        $document = $this->read($path, $generatedFiles);
        $stats = $this->object($document['stats'] ?? null, 'stats');

        $killedByTests = $this->intStat($stats, 'killedCount');
        $killedByStaticAnalysis = $this->intStat($stats, 'killedByStaticAnalysisCount');
        $msi = $this->floatStat($stats, 'msi');
        $coveredMsi = $this->floatStat($stats, 'coveredCodeMsi');

        return new InfectionReport(
            summary: [
                'total_mutants' => $this->intStat($stats, 'totalMutantsCount'),
                'killed' => $killedByTests + $killedByStaticAnalysis,
                'killed_by_tests' => $killedByTests,
                'killed_by_static_analysis' => $killedByStaticAnalysis,
                'escaped' => $this->intStat($stats, 'escapedCount'),
                'errored' => $this->intStat($stats, 'errorCount'),
                'syntax_errors' => $this->intStat($stats, 'syntaxErrorCount'),
                'timed_out' => $this->intStat($stats, 'timeOutCount'),
                'not_covered' => $this->intStat($stats, 'notCoveredCount'),
                'skipped' => $this->intStat($stats, 'skippedCount'),
                'ignored' => $this->intStat($stats, 'ignoredCount'),
                'msi' => $msi,
                'covered_msi' => $coveredMsi,
                'mutation_code_coverage' => $this->floatStat($stats, 'mutationCodeCoverage'),
            ],
            items: $this->items($document, $cwd),
            msi: $msi,
            coveredMsi: $coveredMsi,
        );
    }

    /**
     * @param list<string> $generatedFiles
     *
     * @return array<string, mixed>
     */
    private function read(string $path, array $generatedFiles): array
    {
        $realPath = $this->realFile($path);

        if (! in_array($realPath, $this->realGeneratedFiles($generatedFiles), true)) {
            throw $this->invalidShape('Infection JSON file was not generated by this execution.');
        }

        $size = filesize($realPath);

        if (! is_int($size) || $size > $this->maxBytes) {
            throw $this->invalidShape('Infection JSON file is too large.');
        }

        $contents = file_get_contents($realPath);

        if (! is_string($contents) || trim($contents) === '') {
            throw $this->invalidShape('Infection JSON file is empty.');
        }

        try {
            $decoded = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        } catch (Throwable $throwable) {
            throw $this->invalidShape($throwable->getMessage());
        }

        return $this->object($decoded, 'root');
    }

    private function realFile(string $path): string
    {
        $realPath = realpath($path);

        if (! is_string($realPath) || ! is_file($realPath)) {
            throw $this->invalidShape('Missing or invalid Infection JSON file.');
        }

        return $realPath;
    }

    /**
     * @param list<string> $paths
     *
     * @return list<string>
     */
    private function realGeneratedFiles(array $paths): array
    {
        $realPaths = [];

        foreach ($paths as $path) {
            $realPath = realpath($path);

            if (is_string($realPath) && is_file($realPath)) {
                $realPaths[] = $realPath;
            }
        }

        return array_values(array_unique($realPaths));
    }

    /**
     * @param array<string, mixed> $document
     *
     * @return list<array<string, mixed>>
     */
    private function items(array $document, string $cwd): array
    {
        $items = [];

        foreach ($this->mutationBuckets() as $field => $status) {
            foreach ($this->list($document[$field] ?? [], $field) as $mutation) {
                $items[] = $this->mutationItem($this->object($mutation, $field . '[]'), $status, $cwd);
            }
        }

        return $items;
    }

    /**
     * @return array<string, string>
     */
    private function mutationBuckets(): array
    {
        return [
            'escaped' => 'escaped',
            'timeouted' => 'timed_out',
            'errored' => 'errored',
            'syntaxErrors' => 'syntax_error',
            'uncovered' => 'not_covered',
            'ignored' => 'ignored',
        ];
    }

    /**
     * @param array<string, mixed> $mutation
     *
     * @return array<string, mixed>
     */
    private function mutationItem(array $mutation, string $status, string $cwd): array
    {
        $mutator = $this->object($mutation['mutator'] ?? null, 'mutator');
        $item = [
            'type' => ItemType::Mutation->value,
            'status' => $status,
            'mutator' => $this->stringValue($mutator, 'mutatorName'),
            'file' => $this->pathNormalizer->normalize($this->stringValue($mutator, 'originalFilePath'), $cwd),
            'line' => $this->intValue($mutator, 'originalStartLine'),
        ];

        $diff = $mutation['diff'] ?? null;

        if (is_string($diff) && $diff !== '') {
            $item['diff'] = $diff;
        }

        $processOutput = $mutation['processOutput'] ?? null;

        if (is_string($processOutput) && $processOutput !== '') {
            $item['process_output'] = $processOutput;
        }

        return $item;
    }

    /**
     * @return array<string, mixed>
     */
    private function object(mixed $value, string $field): array
    {
        if (! is_array($value) || array_is_list($value)) {
            throw $this->invalidShape(sprintf('Infection "%s" must be an object.', $field));
        }

        $object = [];

        foreach ($value as $key => $item) {
            if (! is_string($key)) {
                throw $this->invalidShape(sprintf('Infection "%s" must use string keys.', $field));
            }

            $object[$key] = $item;
        }

        return $object;
    }

    /**
     * @return list<mixed>
     */
    private function list(mixed $value, string $field): array
    {
        if (! is_array($value) || ! array_is_list($value)) {
            throw $this->invalidShape(sprintf('Infection "%s" must be a list.', $field));
        }

        return $value;
    }

    /**
     * @param array<string, mixed> $values
     */
    private function intStat(array $values, string $key): int
    {
        return $this->intValue($values, $key);
    }

    /**
     * @param array<string, mixed> $values
     */
    private function intValue(array $values, string $key): int
    {
        $value = $values[$key] ?? null;

        if (! is_int($value)) {
            throw $this->invalidShape(sprintf('Infection "%s" must be an integer.', $key));
        }

        return $value;
    }

    /**
     * @param array<string, mixed> $values
     */
    private function floatStat(array $values, string $key): float
    {
        $value = $values[$key] ?? null;

        if (! is_int($value) && ! is_float($value)) {
            throw $this->invalidShape(sprintf('Infection "%s" must be numeric.', $key));
        }

        return (float) $value;
    }

    /**
     * @param array<string, mixed> $values
     */
    private function stringValue(array $values, string $key): string
    {
        $value = $values[$key] ?? null;

        if (! is_string($value) || $value === '') {
            throw $this->invalidShape(sprintf('Infection "%s" must be a non-empty string.', $key));
        }

        return $value;
    }

    private function invalidShape(string $message): UserFacingException
    {
        return UserFacingException::withContext(
            errorCode: ErrorCode::ParseFailure,
            message: 'Unable to parse Infection JSON output.',
            hint: 'Use --debug to inspect limited raw output snippets.',
            context: ['reason' => $message],
        );
    }
}
