<?php

declare(strict_types=1);

namespace Sift\Tools\PhpBench;

use Sift\Core\ErrorCode;
use Sift\Core\ItemType;
use Sift\Exceptions\UserFacingException;
use Sift\Tools\Testing\GeneratedXmlReader;
use Sift\Tools\Testing\ReportPathNormalizer;
use SimpleXMLElement;

final readonly class PhpBenchParser
{
    private GeneratedXmlReader $xmlReader;

    public function __construct(
        int $maxBytes = 10_485_760,
        ?GeneratedXmlReader $xmlReader = null,
        private ReportPathNormalizer $pathNormalizer = new ReportPathNormalizer(),
    ) {
        $this->xmlReader = $xmlReader ?? new GeneratedXmlReader(
            label: 'PHPBench XML',
            maxBytes: $maxBytes,
            hint: 'Use the XML dump generated by the current PHPBench run.',
        );
    }

    /**
     * @param list<string> $generatedFiles
     */
    public function parse(string $path, string $cwd, array $generatedFiles): PhpBenchReport
    {
        $xml = $this->xmlReader->read($path, $generatedFiles);

        if ($xml->getName() !== 'phpbench') {
            throw UserFacingException::withContext(
                errorCode: ErrorCode::ParseFailure,
                message: 'Unable to parse PHPBench XML output.',
                hint: 'Use the XML dump generated by the current PHPBench run.',
                context: ['reason' => 'Expected a phpbench root element.'],
            );
        }

        $benchmarks = $this->nodes($xml, '//benchmark');
        $subjects = $this->nodes($xml, '//subject');
        $variants = $this->nodes($xml, '//variant');
        $iterations = $this->nodes($xml, '//iteration');
        $failures = $this->nodes($xml, '//variant/failures/failure');
        $errors = $this->nodes($xml, '//variant/errors/error');

        return new PhpBenchReport(
            summary: [
                'benchmarks' => count($benchmarks),
                'subjects' => count($subjects),
                'variants' => count($variants),
                'iterations' => count($iterations),
                'failures' => count($failures),
                'errors' => count($errors),
            ],
            items: $this->items($benchmarks, $cwd),
        );
    }

    /**
     * @param list<SimpleXMLElement> $benchmarks
     *
     * @return list<array<string, mixed>>
     */
    private function items(array $benchmarks, string $cwd): array
    {
        $items = [];

        foreach ($benchmarks as $benchmark) {
            $benchmarkName = $this->attribute($benchmark, 'class', 'unknown');

            foreach ($benchmark->subject as $subject) {
                $subjectName = $this->attribute($subject, 'name', 'unknown');

                foreach ($subject->variant as $variant) {
                    $parameterSet = $this->attribute($variant->{'parameter-set'}, 'name', 'default');
                    $details = [
                        'benchmark' => $benchmarkName,
                        'subject' => $subjectName,
                        'parameter_set' => $parameterSet,
                    ];
                    $stats = $variant->stats;
                    $measurement = [
                        'type' => ItemType::Benchmark->value,
                        ...$details,
                        'iterations' => count($variant->iteration),
                        'revolutions' => $this->intAttribute($variant, 'revs'),
                    ];

                    foreach (['min', 'max', 'mean', 'mode', 'rstdev', 'stdev'] as $metric) {
                        $value = $this->floatAttribute($stats, $metric);

                        if ($value !== null) {
                            $measurement[$metric] = $value;
                        }
                    }

                    $timeUnit = $this->attribute($variant, 'output-time-unit');
                    $timeMode = $this->attribute($variant, 'output-mode');

                    if ($timeUnit !== '') {
                        $measurement['time_unit'] = $timeUnit;
                    }

                    if ($timeMode !== '') {
                        $measurement['time_mode'] = $timeMode;
                    }

                    $items[] = $measurement;

                    foreach ($this->nodes($variant, 'failures/failure') as $failure) {
                        $items[] = [
                            'type' => ItemType::Issue->value,
                            ...$details,
                            'message' => trim((string) $failure),
                        ];
                    }

                    foreach ($this->nodes($variant, 'errors/error') as $error) {
                        $item = [
                            'type' => ItemType::Error->value,
                            ...$details,
                            'message' => trim((string) $error),
                        ];
                        $file = $this->attribute($error, 'file');
                        $line = $this->intAttribute($error, 'line');
                        $exceptionClass = $this->attribute($error, 'exception-class');

                        if ($file !== '') {
                            $item['file'] = $this->pathNormalizer->normalize($file, $cwd);
                        }

                        if ($line !== null) {
                            $item['line'] = $line;
                        }

                        if ($exceptionClass !== '') {
                            $item['exception_class'] = $exceptionClass;
                        }

                        $items[] = $item;
                    }
                }
            }
        }

        return $items;
    }

    /**
     * @return list<SimpleXMLElement>
     */
    private function nodes(SimpleXMLElement $xml, string $query): array
    {
        $nodes = $xml->xpath($query);

        return is_array($nodes) ? array_values($nodes) : [];
    }

    private function attribute(SimpleXMLElement $node, string $name, string $default = ''): string
    {
        $value = trim((string) $node[$name]);

        return $value === '' ? $default : $value;
    }

    private function intAttribute(SimpleXMLElement $node, string $name): ?int
    {
        $value = $this->attribute($node, $name);

        return ctype_digit($value) ? (int) $value : null;
    }

    private function floatAttribute(SimpleXMLElement $node, string $name): ?float
    {
        $value = $this->attribute($node, $name);

        return is_numeric($value) ? (float) $value : null;
    }
}
