<?php

declare(strict_types=1);

use Sift\Core\ErrorCode;
use Sift\Exceptions\UserFacingException;
use Sift\Tools\Testing\JunitParser;
use Tests\Support\FixtureProject;

it('normalizes junit summary and failing test items', function (): void {
    $project = FixtureProject::create();
    $failureFile = $project->write('tests/Feature/CheckoutTest.php', '<?php');
    $errorFile = $project->write('tests/Feature/ErrorTest.php', '<?php');
    $report = $project->write('build/junit.xml', sprintf(
        <<<'XML'
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Feature" tests="3" failures="1" errors="1" skipped="1">
    <testcase classname="Tests\Feature\CheckoutTest" name="it checks out" file="%s" line="12">
      <failure message="Expected true">Failed asserting that false is true.</failure>
    </testcase>
    <testcase classname="Tests\Feature\ErrorTest" name="it explodes" file="%s">
      <error message="RuntimeException">Thrown at %s:56</error>
    </testcase>
    <testcase classname="Tests\Feature\SkipTest" name="it skips">
      <skipped/>
    </testcase>
  </testsuite>
</testsuites>
XML,
        htmlspecialchars($failureFile, ENT_QUOTES | ENT_XML1),
        htmlspecialchars($errorFile, ENT_QUOTES | ENT_XML1),
        htmlspecialchars($errorFile, ENT_QUOTES | ENT_XML1),
    ));

    $parsed = (new JunitParser())->parse($report, $project->root(), [$report]);

    expect($parsed->summary())->toBe([
        'tests' => 3,
        'passed' => 0,
        'failures' => 1,
        'errors' => 1,
        'skipped' => 1,
    ]);
    expect($parsed->items())->toBe([
        [
            'type' => 'test_failure',
            'test' => 'it checks out',
            'file' => 'tests/Feature/CheckoutTest.php',
            'message' => 'Expected true' . "\n" . 'Failed asserting that false is true.',
            'line' => 12,
        ],
        [
            'type' => 'test_error',
            'test' => 'it explodes',
            'file' => 'tests/Feature/ErrorTest.php',
            'message' => 'RuntimeException' . "\n" . 'Thrown at tests/Feature/ErrorTest.php:56',
            'line' => 56,
        ],
    ]);
});

it('reads only files generated by the current execution', function (): void {
    $project = FixtureProject::create();
    $report = $project->write('build/junit.xml', '<testsuites/>');
    $otherReport = $project->write('build/other.xml', '<testsuites/>');

    expect(fn(): mixed => (new JunitParser())->parse($report, $project->root(), [$otherReport]))
        ->toThrow(UserFacingException::class, 'JUnit XML file was not generated by this execution.');
});

it('rejects doctypes before parsing xml', function (): void {
    $project = FixtureProject::create();
    $report = $project->write('build/junit.xml', <<<'XML'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testsuites [
  <!ENTITY secret SYSTEM "file:///etc/passwd">
]>
<testsuites><testsuite><testcase name="leak"><failure>&secret;</failure></testcase></testsuite></testsuites>
XML);

    try {
        (new JunitParser())->parse($report, $project->root(), [$report]);
    } catch (UserFacingException $userFacingException) {
        expect($userFacingException->errorCode())->toBe(ErrorCode::ParseFailure);
        expect($userFacingException->getMessage())->toBe('JUnit XML doctype is not allowed.');

        return;
    }

    throw new RuntimeException('Expected JUnit parse failure.');
});

it('rejects oversized junit reports', function (): void {
    $project = FixtureProject::create();
    $report = $project->write('build/junit.xml', '<testsuites><testsuite name="' . str_repeat('x', 32) . '"/></testsuites>');

    expect(fn(): mixed => (new JunitParser(maxBytes: 16))->parse($report, $project->root(), [$report]))
        ->toThrow(UserFacingException::class, 'JUnit XML file is too large.');
});
